export const products = [
  {
    id: 1,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/5FcjfPQ/product.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 2,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/P6963HG/product-1.png",
    small_img_url: [
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 3,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/pzxpvvT/product-12.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 4,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/thQdsZ1/product-20.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 5,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/ySgyH8F/product-21.png",
    small_img_url: [
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 6,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/XJx8Vq6/product-19.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 7,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/y5X1n13/product-18.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 8,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/PzFnZzF/product-17.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 9,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/HnYXnQS/product-15.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 10,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/YQ47GFN/product-14.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/YXBfHmL/product-16.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 11,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/thQdsZ1/product-20.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
  {
    id: 12,
    product_name: "Nestle Original Coffee-Mate Coffee Creamer",
    nickname: "Healthy Cashew Nuts",
    product_code: "12314",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam",
    price: 10.0,
    del_price: 20.0,
    rating: 5,
    review: 100,
    discount: 20,
    stock: true,
    main_img_url: "https://i.ibb.co/ftNxKzc/product-13.png",
    small_img_url: [
      "https://i.ibb.co/ySgyH8F/product-21.png",
      "https://i.ibb.co/XJx8Vq6/product-19.png",
      "https://i.ibb.co/thQdsZ1/product-20.png",
      "https://i.ibb.co/y5X1n13/product-18.png",
    ],
    details_benefit: [
      "Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control Direct Full Array",
      "Quantum Dot Technology",
      "Ambient Mode",
      "One Remote Control",
    ],
    full_description:
      "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
    packaging_and_delivery:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
    other_things_of_product:
      "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita ",
  },
];
